### ISSUE TITLE
Add support for automatically creating a 'latest' tag for `crane push` and `crane provision`

### ISSUE THREAD

**Issue by dancrumb** [michaelsauter/crane#120]
It would be nice to have the ability to provision and push images with the `latest` tag via a CLI parameter.

I already version my images numerically, but it's convenient to have a 'moving' tag that points to the latest version, but doing that with crane is not a trivial task.

I'd like something like

`crane provision --latest && crane push --latest`

**Comment by michaelsauter** [comment]
Sorry for the long silence on this one. I think overall, providing `--tag` is useful in a few cases and doesn't hurt people who don't need it. Somehow the whole thing doesn't feel a 100% right, but I'm unsure what would improve the situation under the current approach (which won't change since we're post 1.0), so I think this is the best way to go.

**Comment by michaelsauter** [comment]
Closing since there won't be any more build-related features in Crane, see #195.
