### ISSUE TITLE
Add build instructions in readme

### ISSUE THREAD

**Issue by mishak87** [michaelsauter/crane#167]
Describe how to build crane in readme or make build script self-sufficient.
- [ ] per nitrogen readme - copy-paste the script
- [ ] how to install gox

**Comment by mishak87** [comment]
I can provide pull requests if necessary.

**Comment by bjaglin** [comment]
An similar effort was made in https://github.com/michaelsauter/crane/pull/153

**Comment by mishak87** [comment]
It looks to me that crane is actually application not library so versioning everything would be *the go way* of doing things - including src/ with everything and bin/ in repository. Alternative would be to describe your flow and add setup for it so it can be built automatically.

Maybe it would be best to make docker image which would require mounting docker socket and config file, that would solve installation issues `docker pull crane` and running it would be easy `docker run -v docker.sock:/tmp... -v $(pwd)/config.yml:/config.yml crane lift`. Only binary needed would then be linux amd.
If written properly it would build from source and run it using [golang image](https://registry.hub.docker.com/_/golang/).

**Comment by bjaglin** [comment]
That's what I was about to suggest - that's exactly how we use it: containerized with an embedded config, bind-mounting the client and the socket at runtime. The logic to produce the image is a bit too tight to our system though, so I can't simply extract it, but it's quite easy to do. That would address #166 at the same time I guess?

**Comment by mishak87** [comment]
Yes that would circumvent it :)

**Comment by dreamcat4** [comment]
If we referencee official Go docs (which I am not against). It would help newcomers to not need to trawl through too much disparate documentation. Or if the documentation *IS* disparate, then at least collect those most relevant links together with a little bit of commentary / annotation. Sorry I haven't the patience for that.

But I was working in my fork yesterday. And it turned out there were these 2 place in the source code I have to change / override to get it to build:

```go
diff --git a/main.go b/main.go
index dae7a9b..046ec24 100644
--- a/main.go
+++ b/main.go
@@ -1,7 +1,7 @@
 package main
 
 import (
-	"github.com/michaelsauter/crane/crane"
+	"github.com/dreamcat4/crane/crane"
 )
 
 func main() {
```

an here:

```go
diff --git a/crane/config.go b/crane/config.go
index d4fb4b4..65e7c50 100644
--- a/crane/config.go
+++ b/crane/config.go
@@ -5,7 +5,7 @@ import (
 	"encoding/json"
 	"errors"
 	"fmt"
-	"gopkg.in/v2/yaml"
+	"gopkg.in/yaml.v2"
 	"io/ioutil"
 	"os"
 	"path/filepath"
```

Sorry to bring that here I just thought it might help others. In particular the 1st one - modifying the crane pkg import path (to point to my local fork) in main.go was pretty far from obvious and had to ask on #go-nuts IRC channel about it.

**Comment by mishak87** [comment]
@dreamcat4 I think the second one is just different syntax, isn't it?

**Comment by michaelsauter** [comment]
IMHO all of that is Go-related and not a Crane issue. My view is that we should point to documents if possible, but I don't want to introduce/maintain information about how to setup your Go environment. That includes using forks etc. 

Nitrogen is just the smallest thing possible to record version numbers. I'll probably stick with that until Go has settled on a common approach. Gox is not needed to build Crane, and I just use it to release a new version.

I'm really not sure what additional information we should provide. Happy to be convinced otherwise, but how to setup and write Go is outside the scope of Crane.

**Comment by mishak87** [comment]
@dreamcat4 Probably would be better to discuss it with Tv` or others on #go-nuts IRC channel at [freenode](https://webchat.freenode.net/) they will point you in right direction.

**Comment by mishak87** [comment]
Sorry was busy a this is just a note how to build crane with just checkout and build (without gox):
```sh
# setup
git clone git@github.com:michaelsauter/crane.git
cd crane
mkdir -p bin
wget -N https://raw.githubusercontent.com/lucachr/nitrogen/master/nitrogen && chmod +x nitrogen
# build
docker run \
    --rm \
    -v $(pwd):/go/src/github.com/michaelsauter/crane \
    -w /go/src/github.com/michaelsauter/crane \
    golang:1.4-cross \
    sh -c './nitrogen -i && go build -o bin/crane'
```

**Comment by michaelsauter** [comment]
I've decided that referencing that you can use the Go toolchain to build is good enough for now. That doesn't cover using nitrogen, but then that is just a way for me to record which revisions Crane is using. I'm waiting for some Go dependency solution to gain traction, then use and document that (at this stage, looks like either it's going to be Go native or gb).
