### ISSUE TITLE
Extract build related functionality

### ISSUE THREAD

**Issue by michaelsauter** [michaelsauter/crane#186]
I was thinking about extracting build related functionality from Crane. At this stage, this is just an idea with no concrete plans. It would be great to get some feedback on this.

Here's my reasoning:
* Orchestrating containers and building images seem to be two rather unrelated tasks
* `provision` is one of the two commands not mapping 1:1 to Docker which I'd rather not have. It would not be needed if building an image weren't supported
* Building images is quite limited. E.g. one should be able to create several tags, or run a command in a container and commit the result etc.

So, to me it might make sense to move the building / pushing of images into it's own tool, which is dedicated to that specific tasks. It could then be developed independently of the rest, making it easier to add additional features such as multiple tags.

Not sure what you guys think? Would be interesting to know who's actually using the build functionality.

**Comment by dreamcat4** [comment]
@michaelsauter Well I am using crane's image building functionality. And at the moment, I think it's pretty good!

My thoughts are:

Well building is a part of docker compose. And to maintain feature parity with docker compose i feel in general is a good thing for the crane tool.

Although I don't entirely object to your idea in principal. However I would not really agree upon a regression in functionality to take it out until there was already (as you are suggesting) some equivalent tool which is either as-good-as or better than the current build-in functionality.

To answer: I guess it depends a lot how you actually do it? I mean, I don't really envisage myself being as being any happier in the future, unless such new build tool can still continue to use same shared `crane.yml` input file(s).

So perhaps a plugins system to farm it out would seem more like my preferred solution than a an entirely separate standalone tool that did everything seperately. Although I really don't see a huge benefit to doing that either unless as part of a larger strategy / rewrite trying to make a brand new 'crane 2' that also farmed out all of the other things too. E.g. an entirely modularised software /plugins model. And I'm not really pushing for that either, as crane is still a relatively small tool IMHO. It is monolithic model indeed. But well structured and not too big or messy to find bugs in / add new features too.


*TAGS:*

Actually although I am needing other kinds of build feature (multiple docker files) I really don't seem to have much need for new build tags feature. Perhaps never. Because when building I am using crane as a development tool. So then crane is being used only for local development builds. Which means (while developing them) I don't need to be tagging them.

When they are finally tagged - that is when they are being published. And that part I am doing all with dockerhub's automated builds tool. Which does not need crane whatsoever as takes it's stuff directly from my pushed github repo and is then built remotely on the docker hub servers. And then if my own image development work is all finally finished, I then download back those final public build from docker hub (to be sure I see the same exact image as everyone else gets). It may not be that way is the best or correct way. But it's least hassle / efforts for myself, with my current workflow.

**Comment by dreamcat4** [comment]
Or maybe a standalone build tool would not need to take input from the same crane.yml file to be 'as good as'. But then what would it look like, a new configuration file for that? And would there be enough common code, to be moved into a shared lib, used by both crane + the new standalone build tool?

**Comment by bjaglin** [comment]
I'll be short on this one, because we have never relied on any build functionnality in Crane, and we will not in the foreseeable future.

In my opinion, the fact that docker compose provides the functionality is not really an argument for keeping it - I do feel like the target & the purpose of the 2 tools are slightly different. To me, crane is just a way to facilitate running docker commands in a specific order, revolving around the _runtime_ dependency graph captured via `crane.yml`. Building images might also require ordering, but that's a completely different graph (based on `FROM` instructions), and it seems like something completely orthogonal.

Therefore, I totally agree with you @michaelsauter , and I think a dedicated tool would allow to cover more use cases regarding building/provisioning. I'd really like to see Crane continuing to focus on the runtime.

**Comment by dreamcat4** [comment]
Yep. Had the rest of today to think about it.
+1

Clearly my initial reaction to begin with was to have some reservations. But the more I think about it, all my arguments against this don't seem to hold up to scrutiny. At worst, I simply don't mind either way. But more likely - I would really appreciate this.

For example: feature parity with docker compose tool. Well if we are doing across 2 separate tools. Then in total they still end up doing the same thing combined (or better) than docker compose. It should not matter (to me) in 1 cmd or 2 cmd for that aspect. When considered together they still meet such feature-parity requirement.

Also: it does not matter to me anymore putting build stuff in some different (separate) config file than the main `crane.yml`. And/or in a different separate folder. I've thought about it some more and that aspect really feels OK now. You point about crane provision feeling out-of-place makes sense to me also. I definitely do need to run that command frequently as a part my workflow. Yet it does not actually need to be a `crane ...` subcommand.

**Comment by michaelsauter** [comment]
Cool, thanks for your feedback. I do think a separate file makes sense. There is really very little from the current crane.yml which is needed for building images.

The whole thing came up since I currently have a few images which are relatively complex top build (multiple steps, running containers, multiple tags) and I started using some bash scripts instead of Crane. So yea, that was a little odd.

I'll think a bit more about this and will hopefully make more concrete plans.

Any ideas for names? :)

**Comment by dreamcat4** [comment]
*Well if a crane is meant to be something from a construction site, I guess you would want to name it after some alternative piece of construction / industrial type equipment?*

**Comment by dreamcat4** [comment]
Or how about 'forklift' ?

Since the tool is likely to be less grandiose. And more appropriate to the smaller size of this tool. A forklift is used to load items into the container. Where they are being packed up. Then at some point after that they get lifted by a crane / loaded into docker / ships whatever.

A forklift is a piece of equipment must versatile / useful in a packing plant. Or warehouse / LDC whatever. Makes sense to me.

**Comment by dreamcat4** [comment]
Or if not bother feel obliged to maintain such analogies. Then more options are available to you:

'Docker Build Tool' ---> `dbt`
'Docker Image Build-tool' ---> `dib`
'Docker Image Build Assistant' --> `diba`
'Michael Sauter's Image Builder' --> `msib`

Decide only on a 'placeholder' project name for now. And start development. So long as your choice is unique enough to be search-replaced without affecting any other strings in your project's src folder.

For example, if you decided upon `packer` right now. But it might turn out during development that you need to give your tool a `pack` subcommand. Then `packer pack` ends up becoming a bad choice anymore. You don't know yet how it will turn out. You may end up needing to add other related functionality surrounding the build task too. It may be hard to predict such things. You should be able to change the name again with a quick search-replace. Just so long as you have decided by the time of initial release.

**Comment by michaelsauter** [comment]
Thanks for all the suggestions!

Packer is a no-go though since it already is an awesome tool which builds images: https://www.packer.io/. It can even build Docker images ;)

**Comment by michaelsauter** [comment]
My initial thoughts would be sth like this:

```
registry: "localhost:5000" #optional
repository: "michaelsauter" #optional
images:
  nginx:
    location: "nginx"
    file: "Dockerfile.prod" #optional
    tags: ["$TODAY"]
  ruby:
    location: "github.com/d11wtq/ruby-docker"
  postgres-data
    script: "some-executable"
    tags: ["$REV"]
hooks:
  nginx:
    pre-build:
    post-build:
```

* `hooks` would be identical to what we have in Crane currently, so this raises the question of how to share that code. I guess to some extent, `groups` would make sense here as well
* The options `location` and `file` map to `docker build`, more could be added.
* Sometimes, it can be complicated to build an image, in which case I think sth. like a bash script is the best way to build the image. E.g. you want to do the following: 1) run container A, 2) run some command in container B which makes changes in A, 3) you want to commit the changes in A to produce image Z. I think this would be overly complicated to support in a tool itself, and less flexible than running a script. The convention would be that if you have an image Z in your config, the script produces an image called Z. 
* Supported commands would be `build` and `push`. Each would have some options, e.g. `--no-cache` for build.

**Comment by dreamcat4** [comment]
It looks good. But also:

What if `imageB` may be built `FROM imageA`. Then we must build `imageA` before `imageB`. Because `imageA` is the base image it must always be build before the other one. Maybe either `depends:` key or something like that. It does not have to be as complex as Crane's runtime dependancy mechanism.

**Comment by dreamcat4** [comment]
& you don't necessarily have to use `location:` if you would prefer something else there are other amicable alternatives. Like `build:`, which is the key name used by fig/compose. Or else `context:`, `build-context:`, and `path:`.

**Comment by michaelsauter** [comment]
Short update on this: I recently came across a use case where I found it helpful that Crane can build images. E.g. for images that depend on some local data - so a very "small" layer on top of what is provided.

So build functionality might stay. Not sure about push, that seems to be too much "building images for others", which is not what Crane is all about.

**Comment by michaelsauter** [comment]
I decided to leave all in for now.
