### ISSUE TITLE
Change run / start etc. semantics

### ISSUE THREAD

**Issue by michaelsauter** [michaelsauter/crane#207]
As stated in #195, I'm not entirely happy about the current semantics. Following is a quite drastic change of semantics, but so far, it sounds much better to me. I'm toying with the idea of implementing that for Crane 2.

The basic idea is the following:

* Commands apply to a target (any number of containers or groups)
* Crane does whatever it needs to do in order for the command to work. That means, it will satisfy dependencies automatically if it can.
* There are 2 "dynamic groups": `dependencies` and `affected`. Using them in the target means that the command will be applied to dependencies or affected containers too
* This removes the flags `--cascade-dependencies`, `--cascade-affected` and `--recreate` (see below)

Examples:

* `crane start web`: Creates the `web` container if it does not exist (!). Starts the `web` container if it exists. Does nothing if the `web` container is running. It will also ensure all dependencies of `web` are in their required state (running or existsing).
* `crane run web`: Removes the `web` container if it does exist (!), then runs it. It will also ensure all dependencies of `web` are in their required state (running or existing). Note that it does not remove any of the dependencies before running/starting them. 
* `crane kill web`: Kills the `web` container if it is running, otherwise it does nothing
* `crane lift web`: Provisions the `web` container, then the same as `crane run web`. Note that it does not provision or remove any dependencies before running/starting them.
* `crane run web+dependencies`: Same as `crane run web`, but it will also remove any dependencies before running them. E.g. if `web` has just one link to `postgres`, then `crane run web+dependencies` is the same as `crane run postgres && crane run web`

I understand this is quite different to how it works currently, but I believe it is much better. Some advantages:
* `--cascade-dependencies`, `--cascade-affected` are cumbersome to type or remember
* Maintaining groups to include all dependencies of a container is cumbersome, too
* `crane start` would not always work since a container might not exist yet, but always using `crane run` would lead to warnings that the container was not recreated. With the above proposal, you can either use the "safe" `crane start` or the "dangerous" `crane run` (which equals the current `crane run --recreate`). BTW, I'm unsure whether this violates the Crane principle of "map directly to a Docker command". However, we're already doing some smarts as to whether a command actually needs to run. Also, you could argue that actually running a container even if it exists already is mapping more closely. In the end, I think this is an acceptable trade-off.
* It is much easier to implement `crane run web rails s -p 0.0.0.0`, since that will bring up any required dependencies automatically
* It might allow us to bring up only a subset of linked dependencies via e.g. `--only` in the future: E.g. you have a container `foo`, which links to all containers in groups `bar` and `baz`. If you only want to start `foo` linked to containers `bar`, you can simply type `crane start --only foo+bar`. This is just a thought and the concept is not bullet-proof yet. But maybe something along those lines could work.
* The different types for dependencies and affected containers are overkill IMHO, so this proposal would remove them. If there is a need for targeting only volumes, we could add a new dynamic group for that.

Any feedback?

**Comment by michaelsauter** [comment]
I have a proof of concept for this now, will push it soon. So far I'm happy with it, seems to be nicer to use and the implementation is actually easier than what we have right now.

At the moment, it does not support `--ignore-missing`. My suggested replacement would be `--exclude <target>`, which would also remove the need for `--only` IMO. Basically, all containers specified via the `exclude` target will be removed from the graph.

**Comment by bjaglin** [comment]
This is indeed quite a change :) I think I need a bit more time to think about it, but here is some feedback.

Let me sum up how I interpreted your initial proposal and your remark to see if we are on the same page:
* Commands issued via the CLI describe the expected final state
  * The containers constrained for that final state are passed as part of the command, either explicitly or via group references
* Crane will take care of preconditions ("dependencies") and side effects ("affected") so that the global state for all the containers listed in the config is consistent at the end
  * This behavior can be turned off completely using the `--only` flag, or selectively using the `--exclude` flag
    * In that case, Crane might prevent the run because of missing dependencies. Passing `--ignore-missing` will allow to adapt the configuration to be able

Some thoughts:
* Since we are moving into a declarative model more than an imperative one, maybe we should not be using verbs in the commands, but present or past participle:  `crane running`, `crane started`, `crane killed` (there could be aliases but the doc should not use verbs to emphasize the "desired state" nature of the command).
* We should ban or define clearly the term target, since it's unclear to me if that's the explicit set of containers passed in the CLI or the set of containers on which we will apply some commands
* I still don't really like the `foo+bar` syntax to affect `foo` and `bar`, but I must say I don't have a better proposal.

**Comment by michaelsauter** [comment]
Please see a preliminary implementation at #208. Feels much better to me already.


Additional remarks:
* I don't think now that we need `--only`. Just `--exclude` will do fine. It's not yet implemented though.
* I restricted the implementation to one target, so no `foo+bar`. If we need more flexibility, maybe we can come back to referencing groups in groups
* I want to stick with 1:1 mapping of Crane vs Docker commands, so `run` etc.
* I use "target" now to refer to the containers that Crane will apply the specified command to, and "unit of work" as all containers which might be affected by this command (and for which Crane might need to do something to fulfill the command)

**Comment by michaelsauter** [comment]
Implemented in #212.
