### ISSUE TITLE
multiple networks

### ISSUE THREAD

**Issue by pdwinkel** [michaelsauter/crane#254]
How can you specify multiple networks?
The following gives an error:

```
networks:
   networkA:
   networkB:

...

net: [networkA,networkB]
```

```
> crane run
ERROR: yaml: unmarshal errors:
  line 64: cannot unmarshal !!seq into string
```

**Comment by michaelsauter** [comment]
The `net` flag of `docker run` is a string, not an array. So you cannot connect a container to multiple networks during `run`.

At this stage, Crane doesn't offer anything over plain Docker in regards to that feature. So you have to manually connect to a second network later, sorry.

I'm hesitant to make the net flag an array in Crane since the mapping is 1:1 currently. I imagine this feature request will come up with Docker itself and they might add support for it, at which stage Crane can support it too.

Feel free to reopen if you have other ideas how to support it in Crane.

**Comment by bjaglin** [comment]
I guess we could have a list of containers in the network declaration to materialize `docker network connect` (when corresponding containers are in the target/unit of work) within the configuration?
