### ISSUE TITLE
Network subnet and fixed container IP

### ISSUE THREAD

**Issue by michaelsauter** [michaelsauter/crane#264]

**Comment by dreamcat4** [comment]
+1

**Comment by dreamcat4** [comment]
@michaelsauter I dont see any new subnet option for `docker run` in docker-engine 1.10.2. Only `--ip=`. Presumably the subnet is merely that of the docker network being chosen with other `--net=` flag.

So should I just make up a small PR for `--ip=` only?

**Comment by michaelsauter** [comment]
AFAIK you need to create a network with subnet in order to set an IP for a container. So the `subnet` option would go to the network configuration.

**Comment by dreamcat4** [comment]
Ah ok!. Sorry dont want to spend the time adding subnets too, Just because not using over here. Maybe you could work on that part youself?

Another thing about new docker networks:

And this is not related to your use-case. But we can now do public of LAN facing ips now in! Like VM bridged networking. Its awesome! We are discussing it over here: http://stackoverflow.com/questions/35742807/docker-1-10-containers-ip-in-lan

**Comment by michaelsauter** [comment]
I think this is possible in 3.3.0 now: https://github.com/michaelsauter/crane/blob/v3.3.0/CHANGELOG.md
