### ISSUE TITLE
Add support for docker swarm mode

### ISSUE THREAD

**Issue by lhenry7** [michaelsauter/crane#315]
Since even docker compose does not support swarm mode services, adding support for swarm mode (where the service and run semantics converge) would be great. Ther is another project called docker-compose-swarm-mode that supports this mostly, but doesn't support all options. ('depends_on' being the one I most wished it supported)

**Comment by michaelsauter** [comment]
Phew. I haven't played aroung with Swarm mode yet. So not entirely sure what Crane would need to do in order to support it. Also keep in mind that Crane (at least originally) is intended for development / CI usage (though it is used in production as well).

So ... I don't have a need for it right now, so won't implement it even though I like the idea. If you or anyone else wants to add it, I'll definitely try to get the PR merged.

**Comment by michaelsauter** [comment]
I'm going to close this as I think Crane will not support this use case going forward. Crane is aimed at dev/CI where you don't need Swarm. However, Crane 3 can read docker-compose files, so it is easy to have one config file in which you can use Crane for dev and docker-compose for Swarm related stuff.
