### ISSUE TITLE
Feature request: Add support for multiple networks à la docker compose

### ISSUE THREAD

**Issue by inthroxify** [michaelsauter/crane#316]
Docker has the ability to create named isolated networks using the "Container Network Model", and subsequently plop containers into multiple networks at once. \([Rudimentary example and diagram here.](http://container42.com/2015/10/30/docker-networking-reborn/)\)

Docker compose now [has support for assigning multiple networks to a container](https://docs.docker.com/compose/networking/#/specifying-custom-networks) as well. When comparing compose networking configuration syntax to Crane, it actually appears very similar to the Crane definition syntax for networks, except that in Crane, the `net:` directive for containers is a string instead of an array, indicating there is not full support for CNM in Crane at this time. It is a bit confusing that multiple networks can be declared but not necessarily assigned.

IMHO Crane is much better than compose (groups and hooks are genius btw), however compose seems to be ahead in terms of support for networking. Is there a chance Crane could support multiple networks in a manner similar to compose?

For now I am working around this problem with hook hacks.

**Comment by michaelsauter** [comment]
Oh okay. `net` was a string in the beginning and I didn't realize it's an array now. This can be changed of course. However, it is not a one-liner since `net` is also used for dependency resolution.

Have you looked into Crane's code yet? It's quite simple, maybe you can figure out how to add it in? Otherwise it goes on my list of things to do next, but I can't make any promises.

**Comment by inthroxify** [comment]
I understand. Docker seems to be advancing at such a pace, it is a proverbial blur. I hope that I did not come across as critical; my goal was to briefly inform as best I could about the scenario.

I did end up looking at the code, and it is impressive and clean, but I am not particularly familiar with the intimacies of the Go language at this time. I would _love_ to contribute, however, I likewise can't make any promises, especially regarding turnaround time, nor the quality of the code I'd produce. I certainly cannot approach it this week at the very least, so consider me as inactive on the issue until such time that I post otherwise, unfortunately.

I'd also be concerned about any "political" design issues arising, as, as you said, `net` is used for dependency resolution at this time, and changes to it might force the use of explicit dependency declaration via the `requires` directive which could be controversial (the decision would be above me, certainly) as the feature is currently listed as experimental. IMO, explicit is better than implicit, but EMMV. Then there may be the question of whether to augment any user-declared dependencies using the networks automatically (or not, I'd say, because it might be impossible to determine the user's intent with a complicated multi-network setup, as well as the associated -- and so-far undiscussed -- docker "[network services](https://docs.docker.com/engine/swarm/networking/#/attach-a-service-to-an-overlay-network)" system which seems to be some kind of multi-homing implementation). Or perhaps it might be better to leave `net` as-is for backwards-compatibility purposes and provide a separate `networks` directive under the container node along the lines of compose's `networks` syntax, which would have the added benefit of helping those who are abandoning compose with their inevitable yaml conversion, and intuitive correlation with the root `networks` directive.

I don't think the networks situation is a dire issue, but at the very least be something to be aware of going forward.

**Comment by michaelsauter** [comment]
No worries! I was glad to hear you enjoy Crane, and thanks for bringing to my attention that `net` is an array now.

Also, thanks for your detailed explanation of possible issues you see. It looks like there's more to it than what it seems.

My initial gut reaction would be to re-iterate what Crane always tries to do: map 1:1 to Docker commands, so I'd prefer to extend `net` to an array, and just follow through with what that means for dependency resolution. But then again, I'd need to read up on all the possibilities to figure out what is best. I only use `net` with one custom network at the moment.

Let me know if you get the chance to implement sth, otherwise I'll update when I get to it.

**Comment by michaelsauter** [comment]
I just released 3.3.0 with plenty of new features, one of them support for multiple networks: https://github.com/michaelsauter/crane/blob/v3.3.0/CHANGELOG.md.
