### ISSUE TITLE
Change CLI library

### ISSUE THREAD

**Issue by michaelsauter** [michaelsauter/crane#48]
Crane currently uses https://github.com/spf13/cobra. However, I found Cobra not ideal and am looking for a replacement.

Requirements:
* Subcommands
* Auto-generated help and usage
* Positional arguments (maybe for use as target)
* Shortflag combining

At the moment, I'm looking at https://github.com/codegangsta/cli (which seems to be quite popular, but lacks in features IMHO) and https://github.com/alecthomas/kingpin (which ticks all the boxes so far).

**Comment by bjaglin** [comment]
Thinking about how we could get shell completion, I got back to that thread, and went through an extensive feature check of the 2 challengers, since current usage and needs have changed compared to what the description says:

feature | Crane status | cobra | kingpin | cli
--- | --: | :-: | :-: | :-:
subcommands | needed | ✓ | ✓ | ✓
auto-generated help & usage | very nice to have | ✓ | ✓ | ✓
enum values | needed for cascading values | untyped, adhoc handling currently | ✓ | `GenericFlag` makes it possible
positional arguments | needed for targets | ✓ |  ✓ with type checks | ✓
flags and positional arguments can be interleaved | users may rely on it | ✓ | ✗ | ✗
shortflag combining | users may rely on it | ✓ | ✓ | ✗
flag value directly after short option | users may rely on it | ✓ | [only in unstable-v2](https://github.com/alecthomas/kingpin/issues/26) | ✓
prefix matching for commands | users may rely on it | ✓ | ✗ | ✗
repeated flags | not needed ATM  | ✗ | ✗ | ✓
built-in bash completion | would allow introducing that feature easily | ✗ | ✗ | ✓

This should give better grounds when/if moving away from cobra, as well as non-documented features we would loose (tagged "users may rely on it"). Looking at this, I can't really see a clear winner at the moment...

**Comment by michaelsauter** [comment]
While thinking about allowing users to specify a command via the CLI, I came back to this issue.

Cobra allows flags and positional arguments to be interleaved. This might be nice to have but conflicts with specifying commands (e.g. `crane run web rails s -p 0.0.0.0`) as Cobra would interpret flags of the command as flags to Cobra.

I had another look at kingpin, and it's looking really good now. Version 2 is declared stable now. It also allows interspersed flags but they can be disabled.

The only regression I see is the prefix matching. This is nice to have, but I'm willing to sacrifice this for the benefits that kingpin provides. Also, removing it won't break any scripts so it's not that bad IMHO.

Therefore, I'm working on replacing Cobra with Kingpin.

**Comment by michaelsauter** [comment]
This is happening on #212.
